version: "2"
services:
  app:
    build: .
    command:
      [ "foreman", "start", "-p", "3000"]
    environment:
      DISABLE_SPRING: "1"
      HOME: "/app"
    ports:
      - "5000:3000"
    volumes:
      - ".:/app"
      - "bundle:/bundle"
    links:
      - "pg"
    user: "${UID}:${GID}"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
    environment:
      RAILS_ENV: "${RAILS_ENV}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"

  pg:
    image: postgres:9.6
    ports:
      - '5438:5432'
    environment:
      POSTGRES_DB:       fastladder
      POSTGRES_USER:     fastladder
    volumes:
      - 'data:/var/lib/postgresql/data'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"

volumes:
  bundle:
    driver: 'local'
  data:
    driver: 'local'
